### ISSUE TITLE
Can not download the tud-campus and tud-crossing test sequences

### ISSUE THREAD

**Issue by VincentHFZ** [rodrigob/barinova_pedestrians_detection#5]
Download the tud-campus and tud-crossing test sequences, every time I try to get into the website, I saw 'EOF'. Where can I get the data?

**Comment by Luna2199** [comment]
YOU CAN GOT THEM IN WEB: https://www.d2.mpi-inf.mpg.de/andriluka_cvpr08

**Comment by VincentHFZ** [comment]
@lanzhou2012 Thanks, I already found it.

**Comment by VincentHFZ** [comment]
The dataset's website is in https://www.d2.mpi-inf.mpg.de/andriluka_cvpr08
